# Use the latest official micromamba image as the base image
FROM docker.io/mambaorg/micromamba:latest

# Change to the root user in order to install OS packages
USER root

# Update apt and install git
RUN apt-get update && apt-get install -y git-all

# Set the working directory in the container to /home/mambauser/app
WORKDIR /home/mambauser/app

# Run git clone to get the repo contents in to /home/mambauser/app
RUN git clone https://github.com/ProjectPythia/ERA5_interactive-cookbook.git

# Create a conda environment from the environment.yml file included in the repo
RUN micromamba env create -f ERA5_interactive-cookbook/environment.yml
# Activate the environment by providing ENV_NAME as an environment variable at runtime 

# Copy the notebook with the panel application to the working directory
RUN mv ERA5_interactive-cookbook/notebooks/04_dashboard.ipynb .

# Remove the rest of the repository as no other files are required 
RUN rm -r ERA5_interactive-cookbook/

# Make panel application port to the world outside this container
EXPOSE 5006

# Set the user to be mambauser instead of root when the container runs
USER mambauser

# Specify the command to run that starts the application
CMD ["panel", "serve", "04_dashboard.ipynb", "--allow-websocket-origin=*", "--autoreload"]